import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
          <article className="prose">
            <h1 className="justify-self-center">WebAuthn Demo</h1>
          </article>
        <div className="grid gap-4">
          <div></div>
          <button className="btn w-24 justify-self-center">Login</button>
          <button className="btn w-24 justify-self-center">Logout</button>
        </div>
      </main>
    </>
  );
};

export default Home;
